In [11]:
# load the daily data, then calculate the value of it 

#df['value_ema_1_beta_99'] = df['diff_ema_1'].shift(-1).fillna(0) + \
#0.99 * df['value_ema_1_beta_99'].shift(-1).fillna(0)

In [12]:
import pandas as pd
import numpy as np

df = pd.read_json('../data/AAPL/data')

In [13]:
df.tail()

,timestamp,open,high,low,close,volumn
2512,2022-01-20 14:30:00,166.979996,169.679993,164.179993,164.509995,91420500
2513,2022-01-21 14:30:00,164.419998,166.330002,162.300003,162.410004,122501300
2514,2022-01-24 14:30:00,160.020004,162.300003,154.699997,161.619995,162706700
2515,2022-01-25 14:30:00,158.979996,162.759995,157.020004,159.779999,115798400
2516,2022-01-26 14:30:00,163.500000,164.389999,157.820007,159.690002,107740600

In [14]:
df['date']=pd.to_datetime(df['timestamp']).apply(lambda x: x.date())
df['time']=pd.to_datetime(df['timestamp'])

In [15]:
df.tail()

,timestamp,open,high,low,close,volumn,date,time
2512,2022-01-20 14:30:00,166.979996,169.679993,164.179993,164.509995,91420500,2022-01-20,2022-01-20 14:30:00
2513,2022-01-21 14:30:00,164.419998,166.330002,162.300003,162.410004,122501300,2022-01-21,2022-01-21 14:30:00
2514,2022-01-24 14:30:00,160.020004,162.300003,154.699997,161.619995,162706700,2022-01-24,2022-01-24 14:30:00
2515,2022-01-25 14:30:00,158.979996,162.759995,157.020004,159.779999,115798400,2022-01-25,2022-01-25 14:30:00
2516,2022-01-26 14:30:00,163.500000,164.389999,157.820007,159.690002,107740600,2022-01-26,2022-01-26 14:30:00

In [16]:
df['close_log'] = np.log(df['close'])
df['close_log_diff']=df['close_log'].diff().fillna(0)

In [17]:
df.head()

,timestamp,open,high,low,close,volumn,date,time,close_log,close_log_diff
0,2012-01-27 14:30:00,15.869286,16.017143,15.848929,15.974286,299709200,2012-01-27,2012-01-27 14:30:00,2.770980,0.000000
1,2012-01-30 14:30:00,15.918214,16.210714,15.906786,16.178928,379341200,2012-01-30,2012-01-30 14:30:00,2.783710,0.012729
2,2012-01-31 14:30:00,16.271070,16.365713,16.181070,16.302856,391683600,2012-01-31,2012-01-31 14:30:00,2.791340,0.007631
3,2012-02-01 14:30:00,16.371786,16.392500,16.269644,16.292500,270046000,2012-02-01,2012-02-01 14:30:00,2.790705,-0.000635
4,2012-02-02 14:30:00,16.282143,16.327499,16.213572,16.254286,186796400,2012-02-02,2012-02-02 14:30:00,2.788357,-0.002348

In [18]:
df['value']=0
for i in range(20):
    df['value']=df['close_log_diff'].shift(-1).fillna(0)+0.9*df['value'].shift(-1).fillna(0)

In [19]:
df.tail(20)

,timestamp,open,high,low,close,volumn,date,time,close_log,close_log_diff,value
2497,2021-12-29 14:30:00,179.330002,180.630005,178.139999,179.380005,62348900,2021-12-29,2021-12-29 14:30:00,5.189506,0.000502,-0.041793
2498,2021-12-30 14:30:00,179.470001,180.570007,178.089996,178.199997,59773000,2021-12-30,2021-12-30 14:30:00,5.182906,-0.006600,-0.039103
2499,2021-12-31 14:30:00,178.089996,179.229996,177.259995,177.570007,64062300,2021-12-31,2021-12-31 14:30:00,5.179365,-0.003542,-0.039513
2500,2022-01-03 14:30:00,177.830002,182.880005,177.710007,182.009995,104487900,2022-01-03,2022-01-03 14:30:00,5.204062,0.024697,-0.071344
2501,2022-01-04 14:30:00,182.630005,182.940002,179.119995,179.699997,99310400,2022-01-04,2022-01-04 14:30:00,5.191289,-0.012773,-0.065079
2502,2022-01-05 14:30:00,179.610001,180.169998,174.639999,174.919998,94537600,2022-01-05,2022-01-05 14:30:00,5.164329,-0.026960,-0.042355
2503,2022-01-06 14:30:00,172.699997,175.300003,171.639999,172.000000,96904000,2022-01-06,2022-01-06 14:30:00,5.147494,-0.016834,-0.028356
2504,2022-01-07 14:30:00,172.889999,174.139999,171.029999,172.169998,86580100,2022-01-07,2022-01-07 14:30:00,5.148482,0.000988,-0.032605
2505,2022-01-10 14:30:00,169.080002,172.500000,168.169998,172.190002,106765600,2022-01-10,2022-01-10 14:30:00,5.148599,0.000116,-0.036356
2506,2022-01-11 14:30:00,172.320007,175.179993,170.820007,175.080002,76138300,2022-01-11,2022-01-11 14:30:00,5.165243,0.016644,-0.058890
2507,2022-01-12 14:30:00,176.119995,177.179993,174.820007,175.529999,74805200,2022-01-12,2022-01-12 14:30:00,5.167810,0.002567,-0.068285
2508,2022-01-13 14:30:00,175.779999,176.619995,171.789993,172.190002,84505800,2022-01-13,2022-01-13 14:30:00,5.148599,-0.019211,-0.054527
2509,2022-01-14 14:30:00,171.339996,173.779999,171.089996,173.070007,80355000,2022-01-14,2022-01-14 14:30:00,5.153696,0.005098,-0.066249
2510,2022-01-18 14:30:00,171.509995,172.539993,169.410004,169.800003,90956700,2022-01-18,2022-01-18 14:30:00,5.134621,-0.019075,-0.052416
2511,2022-01-19 14:30:00,170.000000,171.080002,165.940002,166.229996,94815000,2022-01-19,2022-01-19 14:30:00,5.113372,-0.021249,-0.034630
2512,2022-01-20 14:30:00,166.979996,169.679993,164.179993,164.509995,91420500,2022-01-20,2022-01-20 14:30:00,5.102971,-0.010401,-0.026921
2513,2022-01-21 14:30:00,164.419998,166.330002,162.300003,162.410004,122501300,2022-01-21,2022-01-21 14:30:00,5.090124,-0.012847,-0.015638
2514,2022-01-24 14:30:00,160.020004,162.300003,154.699997,161.619995,162706700,2022-01-24,2022-01-24 14:30:00,5.085248,-0.004876,-0.011957
2515,2022-01-25 14:30:00,158.979996,162.759995,157.020004,159.779999,115798400,2022-01-25,2022-01-25 14:30:00,5.073798,-0.011450,-0.000563
2516,2022-01-26 14:30:00,163.500000,164.389999,157.820007,159.690002,107740600,2022-01-26,2022-01-26 14:30:00,5.073234,-0.000563,0.000000

In [20]:
def gradeToNum(grade):
    return {
        'Buy':1,
        'Overweight':2,
        'Outperform':2,
        'Sell':5,
        'Neutral':3,
        'Hold':3,
        'Equal-Weight':3,
        'Underweight':4,
        'Market Outperform':2,
        'Market Perform':3,
        'Strong Buy': 0,
        'Peer Perform': 3,
        'Underperform':4,
        'Reduce':4,
        'Sector Weight':3,
        'Negative':4,
        'Perform':3,
        'Positive':2,
        'Sector Perform':3,
        'Equal-weight':3,
        'Long-Term Buy':2,
        'Long-term Buy':2,
        'Sector Outperform':2,
        '':3
    }[grade]

In [21]:
df2 = pd.read_json('../data/AAPL/updown')
df2['toGradeNum']=df2['toGrade'].apply(gradeToNum)

In [22]:
df2['date']=pd.to_datetime(df2['epochGradeDate'].astype('timedelta64[s]')).apply(lambda x: x.date())
df2['time']=pd.to_datetime(df2['epochGradeDate'].astype('timedelta64[s]'))

TypeError: dtype timedelta64[ns] cannot be converted to datetime64[ns]

In [241]:
df2.tail()

,action,epochGradeDate,firm,fromGrade,toGrade,toGradeNum,date,time
816,main,1331713260,Canaccord Genuity,,Buy,1,2012-03-14,2012-03-14 08:21:00
817,main,1331705580,Morgan Stanley,,Overweight,2,2012-03-14,2012-03-14 06:13:00
818,main,1331618880,Jefferies,,Buy,1,2012-03-13,2012-03-13 06:08:00
819,main,1331191980,FBN Securities,,Outperform,2,2012-03-08,2012-03-08 07:33:00
820,main,1328775420,Canaccord Genuity,,Buy,1,2012-02-09,2012-02-09 08:17:00

In [242]:
df2 = df2.iloc[::-1]

In [243]:
df2.head()

,action,epochGradeDate,firm,fromGrade,toGrade,toGradeNum,date,time
820,main,1328775420,Canaccord Genuity,,Buy,1,2012-02-09,2012-02-09 08:17:00
819,main,1331191980,FBN Securities,,Outperform,2,2012-03-08,2012-03-08 07:33:00
818,main,1331618880,Jefferies,,Buy,1,2012-03-13,2012-03-13 06:08:00
817,main,1331705580,Morgan Stanley,,Overweight,2,2012-03-14,2012-03-14 06:13:00
816,main,1331713260,Canaccord Genuity,,Buy,1,2012-03-14,2012-03-14 08:21:00

In [244]:
grouped = df2.groupby('firm')

In [245]:
alist = [grouped.get_group(x) for x in grouped.groups]

In [246]:
alist[9]

,action,epochGradeDate,firm,fromGrade,toGrade,toGradeNum,date,time
798,down,1333954800,BTIG Research,,Neutral,3,2012-04-09,2012-04-09 07:00:00
687,up,1363247623,BTIG Research,Neutral,Buy,1,2013-03-14,2013-03-14 07:53:43
451,main,1460012964,BTIG Research,,Buy,1,2016-04-07,2016-04-07 07:09:24
449,main,1461711804,BTIG Research,,Buy,1,2016-04-26,2016-04-26 23:03:24
426,main,1469593715,BTIG Research,,Buy,1,2016-07-27,2016-07-27 04:28:35
395,main,1473926891,BTIG Research,,Buy,1,2016-09-15,2016-09-15 08:08:11
383,main,1600853202,BTIG Research,Buy,Buy,1,2020-09-23,2020-09-23 09:26:42

In [247]:
i = 0
for df_updown in alist:
    print(i)
    companyName = df_updown['firm'].iloc[0]
    df_updown.rename(columns={'toGradeNum': companyName}, inplace=True)
    df = pd.merge_asof(df, df_updown[['time',companyName]].sort_values(by=['time']), on='time')

0
0
0
0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)
/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

0
0

/home/ken/.local/lib/python3.6/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [248]:
df.tail()

,close,high,low,open,timestamp,volumn,date,time,close_log,close_log_diff,...,Stifel Nicolaus,Susquehanna,Telsey Advisory Group,Tigress Financial,Topeka,UBS,Wedbush,Wells Fargo,William Blair,Wolfe Research
2512,164.509995,169.679993,164.179993,166.979996,2022-01-20 14:30:00,91420500,2022-01-20,2022-01-20 14:30:00,5.102971,-0.010401,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0
2513,162.410004,166.330002,162.300003,164.419998,2022-01-21 14:30:00,122501300,2022-01-21,2022-01-21 14:30:00,5.090124,-0.012847,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0
2514,161.619995,162.300003,154.699997,160.020004,2022-01-24 14:30:00,162706700,2022-01-24,2022-01-24 14:30:00,5.085248,-0.004876,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0
2515,159.779999,162.759995,157.020004,158.979996,2022-01-25 14:30:00,115798400,2022-01-25,2022-01-25 14:30:00,5.073798,-0.011450,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0
2516,159.690002,164.389999,157.820007,163.500000,2022-01-26 14:30:00,107740600,2022-01-26,2022-01-26 14:30:00,5.073234,-0.000563,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0

In [1]:
df['close_log_diff'].autocorr()

NameError: name 'df' is not defined

In [266]:
df.iloc[:, 10:].tail()

,value,ABG Sundal Collier,Ameriprise Financial,Argus,Argus Research,Atlantic Equities,Avondale Partners,B of A Securities,BGC Financial,BMO Capital,...,Stifel Nicolaus,Susquehanna,Telsey Advisory Group,Tigress Financial,Topeka,UBS,Wedbush,Wells Fargo,William Blair,Wolfe Research
2512,-0.026921,5.0,1.0,1.0,1.0,4.0,2.0,1.0,3.0,3.0,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0
2513,-0.015638,5.0,1.0,1.0,1.0,4.0,2.0,1.0,3.0,3.0,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0
2514,-0.011957,5.0,1.0,1.0,1.0,4.0,2.0,1.0,3.0,3.0,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0
2515,-0.000563,5.0,1.0,1.0,1.0,4.0,2.0,1.0,3.0,3.0,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0
2516,0.000000,5.0,1.0,1.0,1.0,4.0,2.0,1.0,3.0,3.0,...,1.0,2.0,2.0,0.0,1.0,1.0,2.0,2.0,2.0,3.0

In [291]:
values = df.iloc[:, 10:].fillna(3).corr()

In [292]:
values

,value,ABG Sundal Collier,Ameriprise Financial,Argus,Argus Research,Atlantic Equities,Avondale Partners,B of A Securities,BGC Financial,BMO Capital,...,Stifel Nicolaus,Susquehanna,Telsey Advisory Group,Tigress Financial,Topeka,UBS,Wedbush,Wells Fargo,William Blair,Wolfe Research
value,1.000000,0.008916,-0.096497,-0.063407,0.004051,0.053443,-0.100899,-0.048644,-0.004239,0.120614,...,0.075897,-0.080557,-0.008916,-0.013485,-0.008916,0.163944,0.170940,-0.050500,-0.096664,0.023469
ABG Sundal Collier,0.008916,1.000000,-0.147860,-0.461409,-0.975209,0.778807,-0.147315,-0.035835,0.114011,0.443462,...,-0.093922,-0.175552,-1.000000,-0.479607,-1.000000,-0.076844,-0.046849,-0.586560,-0.365054,0.804942
Ameriprise Financial,-0.096497,-0.147860,1.000000,0.320453,0.151619,-0.189854,0.996318,0.099588,0.099241,-0.226304,...,0.635209,0.842260,0.147860,0.070915,0.147860,0.152487,0.316850,0.252080,0.405036,-0.122515
Argus,-0.063407,-0.461409,0.320453,1.000000,0.473139,-0.592457,0.319273,0.310773,-0.247093,-0.867159,...,0.203554,0.380468,0.461409,0.221295,0.461409,0.166541,0.101535,0.246458,0.791172,-0.382317
Argus Research,0.004051,-0.975209,0.151619,0.473139,1.000000,-0.798605,0.151060,0.030634,-0.116909,-0.454736,...,0.096310,0.180014,0.975209,0.467717,0.975209,0.078797,0.048040,0.601471,0.374334,-0.808043
Atlantic Equities,0.053443,0.778807,-0.189854,-0.592457,-0.798605,1.000000,-0.189155,-0.524550,0.146392,0.569412,...,-0.120597,-0.225411,-0.778807,-0.373521,-0.778807,-0.098669,-0.060155,-0.665897,-0.468735,0.645308
Avondale Partners,-0.100899,-0.147315,0.996318,0.319273,0.151060,-0.189155,1.000000,0.099221,0.107908,-0.224777,...,0.637556,0.839158,0.147315,0.070654,0.147315,0.153384,0.318021,0.251152,0.403544,-0.122063
B of A Securities,-0.048644,-0.035835,0.099588,0.310773,0.030634,-0.524550,0.099221,1.000000,-0.076790,-0.298685,...,0.063259,0.118239,0.035835,0.212604,0.035835,0.051757,0.031554,0.274085,0.245875,0.086863
BGC Financial,-0.004239,0.114011,0.099241,-0.247093,-0.116909,0.146392,0.107908,-0.076790,1.000000,0.068117,...,0.068797,-0.304543,-0.114011,-0.054681,-0.114011,-0.396175,0.034317,-0.036758,-0.312313,0.094468
BMO Capital,0.120614,0.443462,-0.226304,-0.867159,-0.454736,0.569412,-0.224777,-0.298685,0.068117,1.000000,...,-0.055547,-0.165394,-0.443462,-0.212688,-0.443462,-0.024067,0.133481,-0.218766,-0.651467,0.367446
BTIG Research,-0.086310,-0.140138,0.947777,0.303718,0.143701,-0.179940,0.951280,0.094387,0.102651,-0.204405,...,0.670209,0.798274,0.140138,0.067211,0.140138,0.165743,0.334308,0.238916,0.383884,-0.116116
Baird,-0.068257,-0.181835,0.813156,0.394085,0.186457,-0.233478,0.810162,0.122471,-0.387973,-0.184847,...,0.516524,0.965446,0.181835,0.087209,0.181835,0.294509,0.257648,0.300975,0.498103,-0.150665
Bank of America,-0.028196,0.429792,-0.043100,0.076048,-0.440718,0.235327,-0.040995,0.147519,-0.018795,-0.040963,...,0.220410,-0.122887,-0.429792,-0.206131,-0.429792,0.212190,0.129366,-0.241931,0.289707,0.356119
Bank oferica,0.108862,-0.057861,0.391325,0.125401,0.059332,-0.074295,0.392772,0.038971,0.042383,0.114705,...,0.616058,0.329598,0.057861,0.027751,0.057861,0.487545,0.809684,0.098645,0.158501,-0.047943
Barclays,0.158404,0.319519,-0.069725,-0.692485,-0.327642,0.410267,-0.066925,-0.215206,0.356821,0.617456,...,0.192807,-0.201687,-0.319519,-0.153244,-0.319519,-0.088992,0.096174,0.000794,-0.722087,0.264749
Berenberg,0.031102,-0.900155,-0.269727,0.311465,0.874781,-0.670283,-0.271773,-0.006574,-0.154174,-0.338425,...,-0.208085,-0.178152,0.900155,0.431721,0.900155,-0.000387,-0.103795,0.459898,0.184029,-0.723132
Bernstein,0.044852,0.301754,0.286657,-0.553972,-0.309425,0.387457,0.285601,-0.203241,-0.221034,0.677135,...,0.182087,0.340343,-0.301754,-0.144724,-0.301754,0.148977,0.090827,-0.048654,-0.243588,0.250029
Brean Capital,-0.015670,-0.273005,0.541602,0.591675,0.279945,-0.350542,0.539608,0.183877,-0.417616,-0.432677,...,0.344031,0.643035,0.273005,0.130935,0.273005,0.281474,0.171607,0.375595,0.747847,-0.226207
CLSA,-0.059590,-0.211527,0.699012,0.458437,0.216904,-0.271604,0.696438,0.142470,-0.538991,-0.271431,...,0.444019,0.829925,0.211527,0.101450,0.211527,0.363281,0.221482,0.259679,0.579440,-0.175268
Canaccord Genuity,-0.067792,-0.046166,0.312228,0.100054,0.047340,-0.059278,0.313382,0.031094,0.033816,-0.041729,...,0.109629,0.262977,0.046166,0.022142,0.046166,0.142270,0.250627,0.078706,0.126463,-0.038252
Cantor Fitzgerald,-0.080683,-0.172000,0.859650,0.372771,0.176373,-0.220851,0.856485,0.115847,-0.256234,-0.154185,...,0.546057,0.979770,0.172000,0.082492,0.172000,0.117354,0.272380,0.293236,0.471163,-0.142517
Cascend,-0.109495,-0.710634,0.208068,0.649292,0.728700,-0.912465,0.207301,0.478633,-0.160436,-0.624037,...,0.132166,0.247035,0.710634,0.340825,0.710634,0.108134,0.065926,0.582811,0.513702,-0.588821
China Renaissance,-0.008916,-1.000000,0.147860,0.461409,0.975209,-0.778807,0.147315,0.035835,-0.114011,-0.443462,...,0.093922,0.175552,1.000000,0.479607,1.000000,0.076844,0.046849,0.586560,0.365054,-0.804942
Citi,-0.008916,-1.000000,0.147860,0.461409,0.975209,-0.778807,0.147315,0.035835,-0.114011,-0.443462,...,0.093922,0.175552,1.000000,0.479607,1.000000,0.076844,0.046849,0.586560,0.365054,-0.804942
Citigroup,0.026412,-0.193236,0.192871,0.418794,0.198148,-0.248118,0.188458,0.130150,-0.590011,-0.235243,...,0.044104,0.402132,0.193236,0.092677,0.193236,0.397669,0.242447,0.223023,0.529334,-0.160112
Cleveland Research,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cowen & Co.,-0.063154,-0.301240,0.490838,0.652869,0.308898,-0.386796,0.489031,0.202894,-0.378473,-0.501815,...,0.311785,0.582763,0.301240,0.144477,0.301240,0.255092,0.155522,0.161400,0.825192,-0.249603
Credit Agricole,-0.046028,0.415547,0.715651,0.008649,-0.399347,0.264285,0.718877,0.060018,0.146815,0.081404,...,0.622451,0.575572,-0.415547,-0.199299,-0.415547,0.132435,0.310486,-0.112378,0.127206,0.331714
Credit Suisse,0.161801,0.449950,-0.201792,-0.394259,-0.461389,0.577743,-0.200229,-0.303055,-0.032091,0.428778,...,-0.023753,-0.258531,-0.449950,-0.215799,-0.449950,0.222143,0.135434,-0.313665,-0.185895,0.372822
"Crowell, Weedon & Co.",0.164868,-0.048845,0.330350,0.105861,0.050087,-0.062718,0.331571,0.032899,0.035779,0.139168,...,0.520065,0.278240,0.048845,0.023427,0.048845,0.583560,0.959135,0.083275,0.133803,-0.040473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Nomura Instinet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OTR Global,0.090361,0.392489,-0.376724,-0.850631,-0.402467,0.503962,-0.375336,-0.264353,0.290482,0.713847,...,-0.239298,-0.447277,-0.392489,-0.188241,-0.392489,-0.195786,-0.119365,-0.135510,-0.930099,0.325211
Oppenheimer,0.143621,-0.360121,-0.259551,-0.389085,0.334849,-0.116023,-0.258061,-0.194661,0.263787,0.312648,...,-0.096893,-0.333134,0.360121,0.172717,0.360121,-0.033228,0.123279,0.222841,-0.641346,-0.282181
Oracle Investment Research,-0.005955,-0.117450,0.794332,0.254546,0.120436,-0.150807,0.797268,0.079106,0.086032,-0.132742,...,0.822547,0.669034,0.117450,0.056330,0.117450,0.220099,0.410296,0.200235,0.321733,-0.097317
Oxen Group,0.171247,-0.045473,0.307540,0.098552,0.046629,-0.058388,0.308677,0.030627,0.033309,0.129559,...,0.484156,0.259028,0.045473,0.021809,0.045473,0.591757,0.970617,0.077525,0.124565,-0.037678
Pacific Crest,-0.052920,0.434989,0.364636,0.227532,-0.411600,0.211945,0.362979,0.144499,-0.318628,-0.089839,...,0.262485,0.447626,-0.434989,-0.208624,-0.434989,0.214756,0.130930,-0.136467,0.437242,0.344206
Phillip Securities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Piper Jaffray,-0.119546,-0.684238,0.216094,0.674341,0.701632,-0.878572,0.215299,0.460855,-0.166625,-0.648111,...,0.137265,0.256565,0.684238,0.328165,0.684238,0.112306,0.068469,0.549946,0.533519,-0.566949
Piper Sandler,-0.054328,-0.788456,0.187531,0.585206,0.808500,-0.987762,0.186840,0.515048,-0.144600,-0.562444,...,0.119121,0.222652,0.788456,0.378149,0.788456,0.097461,0.059419,0.677476,0.462999,-0.653303
PiperJaffray,0.171247,-0.045473,0.307540,0.098552,0.046629,-0.058388,0.308677,0.030627,0.033309,0.129559,...,0.484156,0.259028,0.045473,0.021809,0.045473,0.591757,0.970617,0.077525,0.124565,-0.037678
RBC Capital,-0.076008,-0.130431,0.882123,0.282679,0.133746,-0.167475,0.885383,0.087849,0.095540,-0.176005,...,0.720091,0.742976,0.130431,0.062555,0.130431,0.184239,0.359190,0.222365,0.357291,-0.108073
Raymond James,-0.088915,0.006481,0.206126,-0.014047,-0.006646,0.008322,0.206660,-0.004365,0.571481,0.027422,...,0.295591,0.015871,-0.006481,-0.003109,-0.006481,-0.219900,0.160351,-0.164395,-0.017755,0.005370
Rosenblatt,0.107469,0.554840,0.033531,-0.472660,-0.568945,0.712423,0.033407,-0.373701,-0.025855,0.534732,...,0.021299,0.039810,-0.554840,-0.266105,-0.554840,0.017426,0.010624,-0.309857,-0.181703,0.459732
Scotiabank,0.044220,0.906268,0.041663,-0.372863,-0.882467,0.692392,0.042835,-0.015543,0.125803,0.449979,...,0.195114,-0.012497,-0.906268,-0.434652,-0.906268,0.117684,0.272784,-0.501885,-0.267790,0.728865
Societe Generale,0.066992,-0.502858,-0.325841,-0.109337,0.480343,-0.290532,-0.323658,-0.109590,0.294725,0.035719,...,-0.081934,-0.430604,0.502858,0.241174,0.502858,-0.008489,0.093166,0.157736,-0.291545,-0.400040
Standpoint,0.032903,0.179880,-0.480196,-0.389849,-0.184453,0.230969,-0.474296,-0.121155,0.785782,0.171620,...,-0.301060,-0.763321,-0.179880,-0.086272,-0.179880,-0.453950,-0.150173,-0.162013,-0.492749,0.149046
Standpoint Research,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sterne Agee,0.169188,-0.047524,0.321409,0.102996,0.048732,-0.061021,0.322597,0.032009,0.034811,0.135402,...,0.505990,0.270710,0.047524,0.022793,0.047524,0.600612,0.985815,0.081021,0.130182,-0.039377
Sterne Agee CRT,-0.059729,-0.300212,0.492519,0.650641,0.307844,-0.385476,0.490705,0.202202,-0.379769,-0.499336,...,0.312852,0.584759,0.300212,0.143984,0.300212,0.255965,0.156055,0.381860,0.822376,-0.248751
Stifel,-0.060893,-0.128967,0.872224,0.279507,0.132246,-0.165596,0.875448,0.086863,0.094468,-0.171627,...,0.728263,0.734639,0.128967,0.061854,0.128967,0.187230,0.363266,0.219870,0.353282,-0.106860
Stifel Nicolaus,0.075897,-0.093922,0.635209,0.203554,0.096310,-0.120597,0.637556,0.063259,0.068797,-0.055547,...,1.000000,0.535011,0.093922,0.045046,0.093922,0.282530,0.498812,0.160123,0.257282,-0.077822
Susquehanna,-0.080557,-0.175552,0.842260,0.380468,0.180014,-0.225411,0.839158,0.118239,-0.304543,-0.165394,...,0.535011,1.000000,0.175552,0.084196,0.175552,0.164129,0.266870,0.299290,0.480892,-0.145459
Telsey Advisory Group,-0.008916,-1.000000,0.147860,0.461409,0.975209,-0.778807,0.147315,0.035835,-0.114011,-0.443462,...,0.093922,0.175552,1.000000,0.479607,1.000000,0.076844,0.046849,0.586560,0.365054,-0.804942
Tigress Financial,-0.013485,-0.479607,0.070915,0.221295,0.467717,-0.373521,0.070654,0.212604,-0.054681,-0.212688,...,0.045046,0.084196,0.479607,1.000000,0.479607,0.036855,0.022469,0.281318,0.175083,0.061854
Topeka,-0.008916,-1.000000,0.147860,0.461409,0.975209,-0.778807,0.147315,0.035835,-0.114011,-0.443462,...,0.093922,0.175552,1.000000,0.479607,1.000000,0.076844,0.046849,0.586560,0.365054,-0.804942
UBS,0.163944,-0.076844,0.152487,0.166541,0.078797,-0.098669,0.153384,0.051757,-0.396175,-0.024067,...,0.282530,0.164129,0.076844,0.036855,0.076844,1.000000,0.609670,0.007572,0.210500,-0.063672
Wedbush,0.170940,-0.046849,0.316850,0.101535,0.048040,-0.060155,0.318021,0.031554,0.034317,0.133481,...,0.498812,0.266870,0.046849,0.022469,0.046849,0.609670,1.000000,0.079872,0.128336,-0.038819
Wells Fargo,-0.050500,-0.586560,0.252080,0.246458,0.601471,-0.665897,0.251152,0.274085,-0.036758,-0.218766,...,0.160123,0.299290,0.586560,0.281318,0.586560,0.007572,0.079872,1.000000,0.087135,-0.486014
William Blair,-0.096664,-0.365054,0.405036,0.791172,0.374334,-0.468735,0.403544,0.245875,-0.312313,-0.651467,...,0.257282,0.480892,0.365054,0.175083,0.365054,0.210500,0.128336,0.087135,1.000000,-0.302478
Wolfe Research,0.023469,0.804942,-0.122515,-0.382317,-0.808043,0.645308,-0.122063,0.086863,0.094468,0.367446,...,-0.077822,-0.145459,-0.804942,0.061854,-0.804942,-0.063672,-0.038819,-0.486014,-0.302478,1.000000

In [294]:
values['value'].sort_values()

Piper Jaffray           -0.119546
Cascend                 -0.109495
Avondale Partners       -0.100899
FBR Capital             -0.098502
Daiwa Capital           -0.097340
William Blair           -0.096664
Ameriprise Financial    -0.096497
Raymond James           -0.088915
BTIG Research           -0.086310
Evercore Partners       -0.082714
Cantor Fitzgerald       -0.080683
Mizuho                  -0.080587
Susquehanna             -0.080557
RBC Capital             -0.076008
Janney Capital          -0.076008
DA Davidson             -0.074635
KeyBanc                 -0.073011
Baird                   -0.068257
Canaccord Genuity       -0.067792
Argus                   -0.063407
Cowen & Co.             -0.063154
Stifel                  -0.060893
Sterne Agee CRT         -0.059729
CLSA                    -0.059590
Drexel Hamilton         -0.058666
Piper Sandler           -0.054328
Pacific Crest           -0.052920
Wells Fargo             -0.050500
Longbow Research        -0.048806
B of A Securities       -0.048644
                           ...
Stifel Nicolaus          0.075897
Monness Crespi Hardt     0.083340
Hudson Square            0.084002
Keybanc                  0.088090
ISI Group                0.089650
OTR Global               0.090361
Rosenblatt               0.107469
Bank oferica             0.108862
HSBC                     0.117220
BMO Capital              0.120614
Oppenheimer              0.143621
JP Morgan                0.147736
FBN Securities           0.155122
Barclays                 0.158404
Credit Suisse            0.161801
UBS                      0.163944
Crowell, Weedon & Co.    0.164868
Sterne Agee              0.169188
Morgan Keegan            0.169188
Wedbush                  0.170940
Oxen Group               0.171247
PiperJaffray             0.171247
Morgan Stanley           0.172009
value                    1.000000
Cleveland Research            NaN
Hamburger Sparkasse           NaN
Instinet                      NaN
Nomura Instinet               NaN
Phillip Securities            NaN
Standpoint Research           NaN
Name: value, Length: 96, dtype: float64