In [15]:
import os
from os import listdir
from os.path import isdir, isfile, join
import pandas as pd

rootdir = '../data/stocks'

stock_list = [f for f in listdir(rootdir) if isdir(join(rootdir, f))]

['TSM',
 'PFE',
 'NVDA',
 'DIS',
 'AAPL',
 'ERIC-B.ST',
 'NSRGY',
 'TSLA',
 'AIR.F',
 'MRK',
 'ESSITY-B.ST',
 'DDAIF',
 'T',
 'GOOGL',
 'AZN.ST',
 'MSFT',
 'INTC',
 'RHHBY',
 'HEXA-B.ST',
 'AMBK',
 'AMZN']

In [12]:
stock_dir = '../data/stocks/AAPL/raw-minute'

In [38]:
file_list = [join(stock_dir, f) for f in listdir(stock_dir) if isfile(join(stock_dir, f))]
data = None
print(file_list)
for file in file_list:
  print(file)
  if data is None:
    data = pd.read_json(file)
    print('first')
    print(len(data))
  else:
    data = pd.concat([data, pd.read_json(file)]).drop_duplicates().reset_index(drop=True)
    print('second')
    print(len(data))
data['date']=data['timestamp']

['../data/stocks/AAPL/raw-minute/data-2022415']
../data/stocks/AAPL/raw-minute/data-2022415
first
1951

AttributeError: 'Series' object has no attribute 'strftime'

In [41]:
data['date']=data['timestamp'].dt.strftime('%Y%m%d')

In [42]:
data

,timestamp,open,high,low,close,volumn,date
0,2022-04-08 13:30:00,171.429993,171.429993,171.419998,171.419998,2151827.0,20220408
1,2022-04-08 13:31:00,171.460007,171.589996,171.289993,171.529999,396831.0,20220408
2,2022-04-08 13:32:00,171.559998,171.649994,171.080002,171.160004,401921.0,20220408
3,2022-04-08 13:33:00,171.139999,171.199905,170.649994,170.759995,483649.0,20220408
4,2022-04-08 13:34:00,170.770004,170.949997,170.690002,170.802902,365293.0,20220408
...,...,...,...,...,...,...,...
1946,2022-04-14 19:56:00,165.369995,165.389999,165.285004,165.300003,319236.0,20220414
1947,2022-04-14 19:57:00,165.315002,165.320007,165.054993,165.070099,605298.0,20220414
1948,2022-04-14 19:58:00,165.080002,165.110001,165.050003,165.086594,633361.0,20220414
1949,2022-04-14 19:59:00,165.085007,165.350006,165.039993,165.279999,1331119.0,20220414
1950,2022-04-14 20:00:00,165.289993,165.289993,165.289993,165.289993,0.0,20220414

In [45]:
grouped = data.groupby('date')
stock_dir = '../data/stocks/AAPL'
os.mkdir(os.path.join(stock_dir, 'daily'))
for name, group in grouped:
  print(name)
  group.to_json(f'../data/stocks/AAPL/daily/data-{name}')
os.remove("demofile.txt")

20220408
20220411
20220412
20220413
20220414

In [57]:
from pathlib import Path

def handle_stock_min(path, stock_name):
  stock_dir = os.path.join(path, stock_name)
  raw_data_dir = os.path.join(stock_dir, 'raw-minute')
  file_list = [join(raw_data_dir, f) for f in listdir(raw_data_dir) if isfile(join(raw_data_dir, f))]
  data = None
  for file in file_list:
    if data is None:
      data = pd.read_json(file)
      print('first')
      print(len(data))
    else:
      data = pd.concat([data, pd.read_json(file)]).drop_duplicates().reset_index(drop=True)
      print('second')
      print(len(data))
  if data is None:
    return
  data['date']=data['timestamp'].dt.strftime('%Y%m%d')
  grouped = data.groupby('date')
  Path(os.path.join(stock_dir, 'daily')).mkdir(exist_ok=True)
  for name, group in grouped:
    group.to_json(f'{stock_dir}/daily/data-{name}')
  for file in file_list:
    os.remove(file)

In [58]:
for stock in stock_list:
  print(f"Processing stock: {stock}")
  handle_stock_min('../data/stocks', stock)

Processing stock: TSM
Processing stock: PFE
Processing stock: NVDA
Processing stock: DIS
Processing stock: AAPL
Processing stock: ERIC-B.ST
Processing stock: NSRGY
Processing stock: TSLA
Processing stock: AIR.F
Processing stock: MRK
first
1951
Processing stock: ESSITY-B.ST
first
2014
Processing stock: DDAIF
first
1950
Processing stock: T
first
1951
Processing stock: GOOGL
first
1951
Processing stock: AZN.ST
first
2014
Processing stock: MSFT
first
1951
Processing stock: INTC
first
1951
Processing stock: RHHBY
first
1950
Processing stock: HEXA-B.ST
first
2014
Processing stock: AMBK
first
5
Processing stock: AMZN
first
1951

In [ ]:
rootdir = '../data/indicators'

indicator_list = [f for f in listdir(rootdir) if isdir(join(rootdir, f))]
for indicator in indicator_list:
  print(f"Processing indicator: {indicator}")
  handle_stock_min(indicator)